// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXWkbJOD-Ux_dXnl2t8fewcMdSxXdxV2I',
    appId: '1:101185373686:web:c0379c374889e762e033d7',
    messagingSenderId: '101185373686',
    projectId: 'pulse-sync-ed38d',
    authDomain: 'pulse-sync-ed38d.firebaseapp.com',
    storageBucket: 'pulse-sync-ed38d.firebasestorage.app',
    measurementId: 'G-0XYLG9Z6BB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVKmfxCXDD5KNuZ7pC0hk62RPEL8yQp-E',
    appId: '1:101185373686:android:f589fabe4cc35522e033d7',
    messagingSenderId: '101185373686',
    projectId: 'pulse-sync-ed38d',
    storageBucket: 'pulse-sync-ed38d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCROXpiuBB8ghmII_Z0IHbe7NLmFHfZq4g',
    appId: '1:101185373686:ios:6b74ba703735ef6ae033d7',
    messagingSenderId: '101185373686',
    projectId: 'pulse-sync-ed38d',
    storageBucket: 'pulse-sync-ed38d.firebasestorage.app',
    iosBundleId: 'com.example.pulseSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCROXpiuBB8ghmII_Z0IHbe7NLmFHfZq4g',
    appId: '1:101185373686:ios:6b74ba703735ef6ae033d7',
    messagingSenderId: '101185373686',
    projectId: 'pulse-sync-ed38d',
    storageBucket: 'pulse-sync-ed38d.firebasestorage.app',
    iosBundleId: 'com.example.pulseSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXWkbJOD-Ux_dXnl2t8fewcMdSxXdxV2I',
    appId: '1:101185373686:web:9b58b3389614126fe033d7',
    messagingSenderId: '101185373686',
    projectId: 'pulse-sync-ed38d',
    authDomain: 'pulse-sync-ed38d.firebaseapp.com',
    storageBucket: 'pulse-sync-ed38d.firebasestorage.app',
    measurementId: 'G-6CS3GDKKEK',
  );
}
